# Fixture Mode Configuration Example
# Add this section to your existing config.yml

analysis:
  fixture_mode:
    # Enable/disable Fixture mode (default: false)
    enable: false
    
    # Text patterns to replace (default: ["Skip", "Over"])
    rewrite_targets:
      - "Skip"
      - "Over"
    
    # Output file name for fixture analysis (default: "analysis_test.yml")
    output_file: "analysis_test.yml"
    
    # Trace file to record replacement history (default: "analysis_fixture_trace.yml")
    trace_file: "analysis_fixture_trace.yml"
    
    # Maximum replacements per analyze_talk() call (default: 5)
    max_per_call: 5
    
    # Apply to which agents: "others" (exclude self) or "all" (include self)
    apply_to_agents: "others"
    
    # Replacement utterances
    utterances:
      # Default replacements (used when no agent-specific text is defined)
      default:
        - "占いCOの有無を確認したいです。仮投票先と理由を一言でお願いします。"
        - "便乗と早い同調を重く見ます。初期の白黒各1名と根拠を提示ください。"
        - "占い師は潜伏していることを考慮しています。"
        - "村人の視点から見て疑わしいエージェントを教えてください。"
        - "現時点での状況分析をお願いします。"
      
      # Agent-specific replacements (optional)
      by_agent:
        メイ:
          - "メイさん、方針と占い希望先を簡潔に出してください。"
          - "メイさん、現在の推理状況を教えてください。"
        サクラ:
          - "サクラさん、怪しいと思う人物を挙げてください。"
          - "サクラさん、今日の投票先候補について意見をお願いします。"

# Environment variables (override config):
# ANALYSIS_FIXTURE_ENABLE=1                    # Enable fixture mode
# ANALYSIS_FIXTURE_OUTPUT_FILE=test.yml        # Change output file
# ANALYSIS_FIXTURE_TRACE_FILE=trace.yml        # Change trace file  
# ANALYSIS_FIXTURE_TARGETS=Skip,Over,Null      # Change target texts
# ANALYSIS_FIXTURE_MAX_PER_CALL=10             # Change max per call
# ANALYSIS_FIXTURE_APPLY_TO=all                # Apply to all agents
# ANALYSIS_FIXTURE_UTTERANCES_DEFAULT="text1|text2|text3"  # Set default texts (| separated)
# ANALYSIS_UPDATE_SELECT_SENTENCE=1            # Force enable downstream (select_sentence)
# ANALYSIS_UPDATE_INTENTION=1                  # Force enable downstream (intention)