micro_intention:
  summary: Promote human candidate
  description: Highlight the candidate's trustworthy and human-like qualities to sway
    votes.
timestamp: '2025-08-25T13:04:28.249115'
trigger: talk
