micro_intention:
  summary: Start with eerie silence
  description: Enter the room quietly and stand motionless, making intense eye contact
    with each person.
timestamp: '2025-08-25T14:02:42.579212'
trigger: talk
