micro_intention:
  summary: Engage and intrigue audience
  description: Start with a compelling question or fact to spark interest and set
    the stage.
timestamp: '2025-08-25T13:16:32.592161'
trigger: talk
