micro_intention:
  summary: Integrate seamlessly with villagers
  description: Adopt local customs and participate in daily activities to avoid standing
    out.
timestamp: '2025-08-25T13:16:59.669792'
trigger: talk
