micro_intention:
  summary: Analyze evidence thoroughly
  description: Review and evaluate all discussion points and evidence before casting
    a vote.
timestamp: '2025-08-25T13:03:48.624902'
trigger: talk
