micro_intention:
  summary: Share personal story
  description: Open with a relatable personal experience to create a connection with
    the group.
timestamp: '2025-08-25T13:58:13.260178'
trigger: talk
